@startuml

class Handler {
+ handleRequest()
}
class ConcreteHandler1 {
+ handleRequest()
}
class ConcreteHandler2 {
+ handleRequest()
}

Handler <|-- ConcreteHandler1
Handler <|-- ConcreteHandler2
Handler <-- "request" Handler
Client -- Handler

@enduml